// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QnRHiS5i7879xACnRWLZNWEU22TSfb4',
    appId: '1:500334687648:web:30b5d46391d30c943220c5',
    messagingSenderId: '500334687648',
    projectId: 'quizapp-7f0c7',
    authDomain: 'quizapp-7f0c7.firebaseapp.com',
    storageBucket: 'quizapp-7f0c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzABrU9nPewpSmZdnzv-cnpxRtCGdAmYk',
    appId: '1:500334687648:ios:4c48860b8dfa88573220c5',
    messagingSenderId: '500334687648',
    projectId: 'quizapp-7f0c7',
    storageBucket: 'quizapp-7f0c7.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzABrU9nPewpSmZdnzv-cnpxRtCGdAmYk',
    appId: '1:500334687648:ios:4c48860b8dfa88573220c5',
    messagingSenderId: '500334687648',
    projectId: 'quizapp-7f0c7',
    storageBucket: 'quizapp-7f0c7.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6QnRHiS5i7879xACnRWLZNWEU22TSfb4',
    appId: '1:500334687648:web:3e763eb9812193a03220c5',
    messagingSenderId: '500334687648',
    projectId: 'quizapp-7f0c7',
    authDomain: 'quizapp-7f0c7.firebaseapp.com',
    storageBucket: 'quizapp-7f0c7.appspot.com',
  );
}
